image: Visual Studio 2022

environment:
  matrix:
    - DOTNET_SDK_VERSION: "8.0.0" Scify the desired version of .NET SDK

install:
  - ps: |
      dotnet tool install --global dotnet-sonarscanner
      dotnet tool install --global coverlet.console

  # Install specific version of .NET SDK
  - ps: choco install dotnetcore-sdk

build:
  project: namesorter.sln    